// Original Admin Reports contract, queried strictly within the authenticated branch.
// No global report controller is invoked by these handlers.
const db = require('../db/connect')
const { resolveReportRange } = require('../utils/reportRange')
const { getTodayDateOnly, addDaysDateOnly } = require('../utils/date')
const { writeAuditLog } = require('../utils/audit')
const num = value => Number(value || 0)
const monthLabel = ym => new Date(`${ym}-01T12:00:00Z`).toLocaleDateString('en-US', {month:'short',year:'numeric',timeZone:'UTC'})
const statusColors={completed:['bg-emerald-500','text-emerald-600'],pending:['bg-amber-400','text-amber-600'],confirmed:['bg-sky-500','text-sky-600'],cancelled:['bg-red-400','text-red-500'],rescheduled:['bg-violet-400','text-violet-600'],no_show:['bg-slate-400','text-slate-500']}
const readBranchReport=async(req,res)=>{
  let range
  try {range=resolveReportRange(req.query)}catch(e){return res.status(e.statusCode||400).json({message:e.message})}
  const {startDate,endDate}=range, branch=req.branchId, today=getTodayDateOnly(), next30=addDaysDateOnly(today,30)
  const [[summary],[monthly],[statusRows],[sources],[topDoctors],[stockActivity],[stockReasons],[byCategory],[paymentEvents],[billingRows],[invRows],[operations],[requests],[serviceRevenue],[usageRows],[patientMix],[receivables],[usageRevenue]] = await Promise.all([
    db.query(`SELECT COUNT(*) appointments,COUNT(DISTINCT patient_id) unique_patients,COALESCE(SUM(clinic_type='medical'),0) medical,COALESCE(SUM(clinic_type='derma'),0) derma,COALESCE(SUM(status='completed'),0) completed,COALESCE(SUM(status='cancelled'),0) cancelled,COALESCE(SUM(status='no_show'),0) no_show FROM appointments WHERE branch_id=? AND appointment_date BETWEEN ? AND ?`,[branch,startDate,endDate]),
    db.query(`SELECT DATE_FORMAT(appointment_date,'%Y-%m') ym,DATE_FORMAT(appointment_date,'%b %Y') month,COUNT(*) appointments,COUNT(DISTINCT patient_id) patients,COALESCE(SUM(clinic_type='derma'),0) derma,COALESCE(SUM(clinic_type='medical'),0) medical FROM appointments WHERE branch_id=? AND appointment_date BETWEEN ? AND ? GROUP BY ym,month ORDER BY ym`,[branch,startDate,endDate]),
    db.query(`SELECT status,COUNT(*) value FROM appointments WHERE branch_id=? AND appointment_date BETWEEN ? AND ? GROUP BY status`,[branch,startDate,endDate]),
    db.query(`SELECT COALESCE(appointment_source,'online') source,COUNT(*) value FROM appointments WHERE branch_id=? AND appointment_date BETWEEN ? AND ? GROUP BY source ORDER BY value DESC`,[branch,startDate,endDate]),
    db.query(`SELECT d.full_name name,d.clinic_type,(d.clinic_type='derma') is_derma,COUNT(*) appointments,COUNT(DISTINCT a.patient_id) patients,COALESCE(SUM(a.status='completed'),0) completed FROM appointments a JOIN doctors d ON d.id=a.doctor_id AND d.branch_id=a.branch_id WHERE a.branch_id=? AND a.appointment_date BETWEEN ? AND ? GROUP BY d.id,d.full_name,d.clinic_type ORDER BY appointments DESC LIMIT 10`,[branch,startDate,endDate]),
    db.query(`SELECT DATE_FORMAT(logged_at,'%Y-%m') ym,DATE_FORMAT(MIN(logged_at),'%b %Y') month,COALESCE(SUM(type='in'),0) stock_in_actions,COALESCE(SUM(type='out'),0) stock_out_actions,COALESCE(SUM(IF(type='in',qty,0)),0) stock_in,COALESCE(SUM(IF(type='out',qty,0)),0) stock_out FROM inventory_logs WHERE branch_id=? AND DATE(logged_at) BETWEEN ? AND ? GROUP BY ym ORDER BY ym`,[branch,startDate,endDate]),
    db.query(`SELECT movement_type movement_reason,movement_type,COUNT(*) actions,COALESCE(SUM(qty),0) quantity FROM inventory_logs WHERE branch_id=? AND DATE(logged_at) BETWEEN ? AND ? GROUP BY movement_type ORDER BY quantity DESC`,[branch,startDate,endDate]),
    db.query(`SELECT i.category,COUNT(DISTINCT i.id) items,COALESCE(SUM(b.quantity),0) total_stock,COALESCE(SUM(b.quantity*COALESCE(b.unit_cost,0)),0) total_value,COALESCE(SUM(b.quantity*COALESCE(i.selling_price,0)),0) retail_value FROM inventory i LEFT JOIN inventory_batches b ON b.inventory_id=i.id AND b.branch_id=i.branch_id AND b.archived_at IS NULL AND b.quantity>0 WHERE i.branch_id=? AND i.archived_at IS NULL GROUP BY i.category`,[branch]),
    db.query(`SELECT kind,payment_method,ym,SUM(amount) amount,COUNT(*) count FROM (SELECT 'payment' kind,bp.payment_method,DATE_FORMAT(bp.paid_at,'%Y-%m') ym,bp.amount amount,DATE(bp.paid_at) event_date FROM billing_payments bp JOIN billing_records br ON br.id=bp.billing_id WHERE br.branch_id=? AND bp.status IN ('completed','voided') UNION ALL SELECT 'void',bp.payment_method,DATE_FORMAT(COALESCE(bp.voided_at,bp.paid_at),'%Y-%m'),bp.amount,DATE(COALESCE(bp.voided_at,bp.paid_at)) FROM billing_payments bp JOIN billing_records br ON br.id=bp.billing_id WHERE br.branch_id=? AND bp.status='voided' UNION ALL SELECT 'refund',COALESCE(r.payment_method,bp.payment_method),DATE_FORMAT(r.refunded_at,'%Y-%m'),r.amount,DATE(r.refunded_at) FROM billing_payment_refunds r JOIN billing_payments bp ON bp.id=r.payment_id JOIN billing_records br ON br.id=bp.billing_id WHERE br.branch_id=?) events WHERE event_date BETWEEN ? AND ? GROUP BY kind,payment_method,ym`,[branch,branch,branch,startDate,endDate]),
    db.query(`SELECT status,COALESCE(SUM(subtotal),0) subtotal,COALESCE(SUM(total_amount),0) billed,COALESCE(SUM(discount_amount),0) discount,COUNT(*) total FROM billing_records WHERE branch_id=? AND DATE(COALESCE(finalized_at,created_at)) BETWEEN ? AND ? GROUP BY status`,[branch,startDate,endDate]),
    db.query(`SELECT COUNT(*) total_items,COALESCE(SUM(stock<=0),0) out_of_stock,COALESCE(SUM(stock>0 AND stock<=threshold),0) low_stock FROM inventory WHERE branch_id=? AND archived_at IS NULL`,[branch]),
    db.query(`SELECT (SELECT COUNT(*) FROM appointments WHERE branch_id=? AND appointment_date=? AND status IN ('pending','confirmed','rescheduled','in-progress')) today_remaining,(SELECT COUNT(*) FROM appointments WHERE branch_id=? AND appointment_date>? AND status IN ('pending','confirmed','rescheduled')) future_confirmed,(SELECT COUNT(*) FROM appointments WHERE branch_id=? AND status='pending' AND appointment_date>=?) awaiting_approval,(SELECT COUNT(*) FROM queue WHERE branch_id=? AND queue_date=? AND status IN ('waiting','called','in_consultation')) walkin_queue,(SELECT COUNT(*) FROM supply_request_groups WHERE branch_id=? AND status='pending') pending_supply_requests`,[branch,today,branch,today,branch,today,branch,today,branch]),
    db.query(`SELECT COALESCE(SUM(status='pending'),0) pending,COALESCE(SUM(status='approved'),0) approved,COALESCE(SUM(status='rejected'),0) rejected FROM supply_request_groups WHERE branch_id=? AND DATE(requested_at) BETWEEN ? AND ?`,[branch,startDate,endDate]),
    db.query(`SELECT bi.service_name,COUNT(DISTINCT bi.billing_id) bills,COALESCE(SUM(bi.line_total),0) gross_billed_amount,COALESCE(SUM(bi.quantity),0) quantity FROM billing_items bi JOIN billing_records br ON br.id=bi.billing_id WHERE br.branch_id=? AND br.status NOT IN ('draft','voided') AND DATE(COALESCE(br.finalized_at,br.created_at)) BETWEEN ? AND ? GROUP BY bi.service_name ORDER BY gross_billed_amount DESC LIMIT 10`,[branch,startDate,endDate]),
    db.query(`SELECT i.id inventory_id,i.name,i.category,i.item_type,COALESCE(i.uom,i.base_unit,i.unit,'unit') unit,COALESCE(SUM(IF(il.movement_type='clinical_use',il.qty,0)),0) used_in_consultation,COALESCE(SUM(IF(il.movement_type='dispensed',il.qty,0)),0) dispensed_at_checkout,COALESCE(SUM(IF(il.movement_type IN ('clinical_return','dispense_return'),il.qty,0)),0) returned,COUNT(DISTINCT il.reference_id) visits FROM inventory_logs il JOIN inventory i ON i.id=il.inventory_id AND i.branch_id=il.branch_id WHERE il.branch_id=? AND il.movement_type IN ('clinical_use','dispensed','clinical_return','dispense_return') AND DATE(il.logged_at) BETWEEN ? AND ? GROUP BY i.id ORDER BY SUM(IF(il.type='out',il.qty,-il.qty)) DESC LIMIT 30`,[branch,startDate,endDate]),
    db.query(`SELECT COALESCE(SUM(first_visit BETWEEN ? AND ?),0) new_patients,COALESCE(SUM(first_visit<?),0) returning_patients FROM (SELECT patient_id,MIN(appointment_date) first_visit FROM appointments WHERE branch_id=? AND patient_id IN (SELECT DISTINCT patient_id FROM appointments WHERE branch_id=? AND appointment_date BETWEEN ? AND ?) GROUP BY patient_id) x`,[startDate,endDate,startDate,branch,branch,startDate,endDate]),
    db.query(`SELECT COALESCE(SUM(GREATEST(0,br.total_amount-COALESCE(pay.paid,0))),0) outstanding FROM billing_records br LEFT JOIN (SELECT bp.billing_id,COALESCE(SUM(IF(bp.status='completed',bp.amount-COALESCE(bp.refund_amount,0),0)),0) paid FROM billing_payments bp GROUP BY bp.billing_id) pay ON pay.billing_id=br.id WHERE br.branch_id=? AND br.status IN ('pending','ready','partially_paid')`,[branch]),
    db.query(`SELECT bi.source_inventory_id inventory_id,COALESCE(SUM(bi.quantity),0) billed_quantity,COALESCE(SUM(bi.line_total),0) billed_amount FROM billing_items bi JOIN billing_records br ON br.id=bi.billing_id WHERE br.branch_id=? AND br.status NOT IN ('draft','voided') AND bi.item_type='supply' AND bi.source_inventory_id IS NOT NULL AND DATE(COALESCE(br.finalized_at,br.created_at)) BETWEEN ? AND ? GROUP BY bi.source_inventory_id`,[branch,startDate,endDate]),
  ])
  const [batchInfo] = await db.query(`SELECT COALESCE(SUM(quantity*COALESCE(unit_cost,0)),0) cost_value,COALESCE(SUM(quantity*COALESCE(i.selling_price,0)),0) retail_value,COALESCE(SUM(unit_cost<=0 AND quantity>0),0) batches_without_cost,COALESCE(SUM(quantity>0),0) batches_on_hand,COALESCE(SUM(quantity>0 AND expiration_date<?),0) expired,COALESCE(SUM(quantity>0 AND expiration_date BETWEEN ? AND ?),0) expiring_soon FROM inventory_batches b JOIN inventory i ON i.id=b.inventory_id AND i.branch_id=b.branch_id WHERE b.branch_id=? AND b.archived_at IS NULL`,[today,today,next30,branch])
  const inv=batchInfo[0]||{}, ap=summary||{}, allStatuses=statusRows.reduce((sum,row)=>sum+num(row.value),0)
  const amount=kind=>paymentEvents.filter(row=>row.kind===kind).reduce((sum,row)=>sum+num(row.amount),0)
  const gross=amount('payment'),voided=amount('void'),refunded=amount('refund'),collected=gross-voided,net=collected-refunded
  const billed=billingRows.filter(row=>!['voided','draft'].includes(row.status)),unpaid=billingRows.filter(row=>['pending','ready','partially_paid'].includes(row.status))
  const sum=(list,key)=>list.reduce((total,row)=>total+num(row[key]),0)
  const paymentMethods=[...new Set(paymentEvents.map(row=>row.payment_method||'unknown'))]
  const paymentsByMethod=paymentMethods.map(payment_method=>{const rows=paymentEvents.filter(row=>(row.payment_method||'unknown')===payment_method),value=k=>sum(rows.filter(row=>row.kind===k),'amount');return {payment_method,transactions:sum(rows.filter(row=>row.kind==='payment'),'count'),gross:value('payment'),voided:value('void'),refunded:value('refund'),net:value('payment')-value('void')-value('refund'),amount:value('payment')-value('void')-value('refund')}})
  const revenueTrend=[...new Set(paymentEvents.map(row=>row.ym))].sort().map(ym=>{const events=paymentEvents.filter(row=>row.ym===ym),value=k=>sum(events.filter(row=>row.kind===k),'amount');return {ym,month:monthLabel(ym),transactions:sum(events.filter(row=>row.kind==='payment'),'count'),revenue:value('payment')-value('void')-value('refund')}})
  const usageAmounts=new Map(usageRevenue.map(row=>[Number(row.inventory_id),row]))
  const mostUsed=usageRows.map(row=>({...row,used_in_consultation:num(row.used_in_consultation),dispensed_at_checkout:num(row.dispensed_at_checkout),returned:num(row.returned),total_used:Math.max(0,num(row.used_in_consultation)+num(row.dispensed_at_checkout)-num(row.returned)),visits:num(row.visits),billed_quantity:num(usageAmounts.get(Number(row.inventory_id))?.billed_quantity),billed_amount:num(usageAmounts.get(Number(row.inventory_id))?.billed_amount)})).filter(row=>row.total_used>0)
  const [[cfg]]=await db.query('SELECT report_footer FROM clinic_settings WHERE id=1')
  res.json({range:{start_date:startDate,end_date:endDate},clinicSettings:{clinic_name:req.branch.name,address:req.branch.address,phone:req.branch.phone,email:req.branch.email,report_footer:cfg?.report_footer||req.branch.name},monthly,appointmentSummary:{...ap,appointments:num(ap.appointments),unique_patients:num(ap.unique_patients),medical:num(ap.medical),derma:num(ap.derma),completed:num(ap.completed),cancelled:num(ap.cancelled),no_show:num(ap.no_show),new_patients:num(patientMix?.new_patients),returning_patients:num(patientMix?.returning_patients)},statusBreakdown:statusRows.map(row=>({label:String(row.status).replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase()),value:num(row.value),pct:allStatuses?Math.round(num(row.value)/allStatuses*100):0,color:(statusColors[row.status]||['bg-slate-400'])[0],textColor:(statusColors[row.status]||['','text-slate-500'])[1]})),appointmentSources:sources,topDoctors,inventoryStats:{...inv,...invRows,total_value:num(inv.cost_value),total_items:num(invRows?.total_items),cost_value:num(inv.cost_value),retail_value:num(inv.retail_value),out_of_stock:num(invRows?.out_of_stock),low_stock:num(invRows?.low_stock),expired:num(inv.expired),expiring_soon:num(inv.expiring_soon)},stockActivity,stockMovementByReason:stockReasons,inventoryByCategory:byCategory,mostUsedMedicines:mostUsed.filter(row=>row.item_type==='medicine').slice(0,10),mostUsedSupplies:mostUsed.filter(row=>row.item_type!=='medicine').slice(0,10),currentOperations:operations||{},upcomingAppointments:num(operations?.future_confirmed),supplyRequests:requests||{},billingSummary:{gross_billed:sum(billed,'subtotal'),gross_billing:sum(billed,'subtotal'),discounts:sum(billed,'discount'),net_billed:sum(billed,'billed'),collected,net_collected:net,refunded,gross_received:gross,voided_payments:voided,outstanding:num(receivables?.outstanding),pending_receivables:num(receivables?.outstanding),paid_bills:sum(billingRows.filter(row=>row.status==='paid'),'total'),partially_paid_bills:sum(billingRows.filter(row=>row.status==='partially_paid'),'total'),unpaid_bills:sum(unpaid,'total'),pending_bills:sum(unpaid,'total'),draft_bills:sum(billingRows.filter(row=>row.status==='draft'),'total'),voided_bills:sum(billingRows.filter(row=>row.status==='voided'),'total')},paymentsByMethod,serviceRevenue,revenueTrend})
}
const recordBranchExport=async(req,res)=>{await writeAuditLog({userId:req.user.id,userRole:'admin',action:'reports.exported',entityType:'report',branchId:req.branchId,oldValues:null,newValues:{start_date:req.body?.start_date||null,end_date:req.body?.end_date||null},ipAddress:req.ip});res.json({success:true})}
const registerBranchReports=(router,{requireSuper,branchContext,requirePermission})=>{
 for(const [prefix,middle] of [['/my/legacy',[branchContext]],['/workspace/:branchId/legacy',[requireSuper,branchContext]]]){
  router.get(`${prefix}/reports`,...middle,requirePermission('reports'),readBranchReport)
  router.post(`${prefix}/reports/export-audit`,...middle,requirePermission('reports'),recordBranchExport)
 }
}
module.exports={readBranchReport,registerBranchReports}
