import { useEffect, useState } from 'react'
import { useAuth } from '../../context/AuthContext'
import { Link, useParams } from 'react-router-dom'
import { MdArchive } from 'react-icons/md'
import { getAuditArchiveDetail } from '../../services/admin.service'
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/PageState'
import Pagination from '../../components/ui/Pagination'
const fmt=(v)=>v?new Date(v).toLocaleString('en-PH'):'—'
const Admin_AuditArchiveDetail=()=>{const {role}=useAuth();const portalBase=role==='staff'?'/staff':'/admin';const {archiveId}=useParams();const [page,setPage]=useState(1),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{setLoading(true);getAuditArchiveDetail(archiveId,{page,limit:20}).then(setData).catch(e=>setError(e.message||'Could not load archive.')).finally(()=>setLoading(false))},[archiveId,page]);if(loading)return <LoadingState label="Loading archived logs..."/>;if(error)return <ErrorState message={error}/>;const items=data?.items||[],p=data?.pagination||{};return <div className="mx-auto w-full max-w-7xl space-y-5"><div><Link to={`${portalBase}/audit-logs/archive`} className="text-sm font-bold text-slate-500">← Audit Log Archive</Link><h1 className="mt-2 flex items-center gap-2 text-2xl font-black text-slate-900"><MdArchive className="text-amber-500"/>{data?.archive?.archive_code}</h1><p className="mt-1 text-sm text-slate-500">Archived {fmt(data?.archive?.archived_at)} · {Number(data?.archive?.log_count||0).toLocaleString()} logs</p></div><section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{!items.length?<div className="p-5"><EmptyState title="Archive is empty"/></div>:<div className="divide-y divide-slate-100">{items.map((r)=><details key={r.id} className="group p-5"><summary className="cursor-pointer list-none"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold text-slate-800">{r.action}</p><p className="mt-1 text-xs text-slate-500">{r.user_role||'system'} · {r.entity_type||'system'} {r.entity_id?`#${r.entity_id}`:''}</p></div><p className="text-xs text-slate-400">{fmt(r.created_at)}</p></div></summary><div className="mt-4 grid gap-3 md:grid-cols-2"><pre className="overflow-auto rounded-xl bg-slate-50 p-3 text-xs text-slate-600">{r.old_values||'No previous value'}</pre><pre className="overflow-auto rounded-xl bg-slate-50 p-3 text-xs text-slate-600">{r.new_values||'No new value'}</pre></div></details>)}</div>}<div className="border-t border-slate-100 p-4"><Pagination page={p.page||page} totalPages={p.totalPages||1} pageSize={p.limit||20} total={p.total||0} onPageChange={setPage}/></div></section></div>}
export default Admin_AuditArchiveDetail
