import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { MdAdd, MdArrowBack, MdCheck, MdClose, MdDelete, MdPayments } from 'react-icons/md'
import { createBillingCatalogService, deleteBillingCatalogService, getBillingCatalog, getInventory, updateBillingCatalogService } from '../../services/admin.service'
import { useToast } from '../../components/ui/ToastProvider'
import ConfirmDialog from '../../components/ui/ConfirmDialog'
import { LoadingState, ErrorState } from '../../components/ui/PageState'
import { formatMoney, roundMoney } from '../../utils/billingUi'

const CLINIC_TYPES = [{ value: 'all', label: 'All Clinics' }, { value: 'medical', label: 'General Medicine' }, { value: 'derma', label: 'Dermatology' }]
const blankMaterial = () => ({ inventory_id: '', material_name: '', quantity: 1, unit_label: '', notes: '' })
const blank = { category: '', service_name: '', clinic_type: 'all', consultation_fee: 0, profit_percentage: 20, default_price: 0, is_active: 1, materials: [] }
const clinicLabel = (value) => CLINIC_TYPES.find((item) => item.value === value)?.label || value
const toForm = (service) => ({ category: service?.category || '', service_name: service?.service_name || '', clinic_type: service?.clinic_type || 'all', consultation_fee: Number(service?.consultation_fee || 0), profit_percentage: Number(service?.profit_percentage ?? 20), default_price: Number(service?.default_price ?? service?.patient_price ?? service?.suggested_price ?? 0), is_active: Number(service?.is_active) === 1 ? 1 : 0, materials: Array.isArray(service?.materials) ? service.materials.map((m) => ({ inventory_id: m.inventory_id || '', material_name: m.material_name || m.inventory_name || '', quantity: Number(m.quantity || 1), unit_label: m.unit_label || m.inventory_unit || '', notes: m.notes || '' })) : [] })

const Admin_BillingServiceForm = () => {
  const { serviceId } = useParams(); const editing = Boolean(serviceId); const navigate = useNavigate(); const toast = useToast()
  const [form, setForm] = useState(blank); const [inventory, setInventory] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [step, setStep] = useState(1); const [saving, setSaving] = useState(false); const [removeOpen, setRemoveOpen] = useState(false); const [deleting, setDeleting] = useState(false); const [errors, setErrors] = useState({}); const [dirty, setDirty] = useState(false)
  const inventoryMap = useMemo(() => new Map(inventory.map((item) => [Number(item.id), item])), [inventory])

  useEffect(() => { (async () => { setLoading(true); try { const [items, catalog] = await Promise.all([getInventory(), editing ? getBillingCatalog({ includeInactive: true }) : Promise.resolve([])]); setInventory(Array.isArray(items) ? items : []); if (editing) { const found = (Array.isArray(catalog) ? catalog : []).find((item) => Number(item.id) === Number(serviceId)); if (!found) throw new Error('Billing service not found.'); setForm(toForm(found)) } setDirty(false) } catch (err) { setError(err.message || 'Could not load service editor.') } finally { setLoading(false) } })() }, [editing, serviceId])
  useEffect(() => { const beforeUnload = (event) => { if (!dirty) return; event.preventDefault(); event.returnValue = '' }; window.addEventListener('beforeunload', beforeUnload); return () => window.removeEventListener('beforeunload', beforeUnload) }, [dirty])

  const materialCost = useMemo(() => roundMoney(form.materials.reduce((sum, material) => { const item = inventoryMap.get(Number(material.inventory_id)); const packageCost = Number(item?.price || 0); const unitSize = Math.max(1, Number(item?.unit_size || 1)); const usage = String(material.unit_label || '').toLowerCase(); const base = String(item?.base_unit || '').toLowerCase(); const unitCost = usage && base && usage === base ? packageCost / unitSize : packageCost; return sum + (Number(material.quantity || 0) * unitCost) }, 0)), [form.materials, inventoryMap])
  const serviceCost = Math.max(0, Number(form.consultation_fee || 0)); const baseCost = roundMoney(materialCost + serviceCost); const markup = roundMoney(baseCost * (Math.max(0, Number(form.profit_percentage || 0)) / 100)); const suggested = roundMoney(baseCost + markup)
  const update = (key, value) => { setForm((current) => ({ ...current, [key]: value })); setDirty(true) }
  const updateMaterial = (index, key, value) => { setForm((current) => ({ ...current, materials: current.materials.map((m, i) => i === index ? { ...m, [key]: value } : m) })); setDirty(true) }
  const chooseInventory = (index, value) => { const item = inventoryMap.get(Number(value)); setForm((current) => ({ ...current, materials: current.materials.map((m, i) => i === index ? { ...m, inventory_id: value, material_name: item?.name || '', unit_label: item?.base_unit || item?.unit || '' } : m) })); setDirty(true) }

  const payload = () => ({ category: String(form.category || '').trim(), service_name: String(form.service_name || '').trim(), clinic_type: form.clinic_type, consultation_fee: Number(form.consultation_fee || 0), profit_percentage: Number(form.profit_percentage || 0), default_price: Number(form.default_price || 0), is_active: Number(form.is_active) === 1 ? 1 : 0, materials: form.materials.map((m, index) => ({ inventory_id: m.inventory_id || null, material_name: String(m.material_name || '').trim(), quantity: Number(m.quantity || 0), unit_label: String(m.unit_label || '').trim(), unit_cost_override: null, notes: String(m.notes || '').trim(), sort_order: index })).filter((m) => m.inventory_id || m.material_name) })
  const validate = (targetStep = 4) => { const p = payload(); const next = {}; if (targetStep === 1 || targetStep === 4) { if (!p.category) next.category = 'Enter a category.'; if (!p.service_name) next.service_name = 'Enter a service name.'; if (p.consultation_fee < 0) next.consultation_fee = 'Cannot be negative.'; if (p.profit_percentage < 0 || p.profit_percentage > 1000) next.profit_percentage = 'Use 0–1,000%.' } if (targetStep === 2 || targetStep === 4) p.materials.forEach((m, i) => { if (!m.inventory_id && !m.material_name) next[`material_${i}`] = 'Select an inventory item.'; if (!(m.quantity > 0)) next[`qty_${i}`] = 'Quantity must be greater than zero.' }); if ((targetStep === 3 || targetStep === 4) && p.default_price < 0) next.default_price = 'Patient price cannot be negative.'; setErrors(next); return Object.keys(next).length === 0 }
  const move = (next) => { if (next > step && !validate(step)) { toast.warning('Check the highlighted fields before continuing.'); return } if (step === 2 && next === 3 && Number(form.default_price || 0) === 0 && suggested > 0) update('default_price', suggested); setStep(next); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const save = async () => {
    if (!validate(4)) { toast.warning('Check the service details before saving.'); return }
    const patientPrice = Number(form.default_price || 0)
    if (Number(form.is_active) === 1 && patientPrice === 0 && !window.confirm('This active service has a ₱0 patient price and will be billed as free. Save it as a free service?')) return
    if (patientPrice > 0 && patientPrice + 0.001 < baseCost && !window.confirm(`Patient Price ${formatMoney(patientPrice)} is below the estimated cost base ${formatMoney(baseCost)}. Save this below-cost price anyway?`)) return
    setSaving(true)
    try { editing ? await updateBillingCatalogService(serviceId, payload()) : await createBillingCatalogService(payload()); setDirty(false); toast.success(editing ? 'Billing service updated.' : 'Billing service added.'); navigate('/admin/billing/setup/services') }
    catch (err) { toast.error(err.message || 'Billing service could not be saved.') }
    finally { setSaving(false) }
  }
  const remove = async () => { setDeleting(true); try { const result = await deleteBillingCatalogService(serviceId); toast.success(result?.message || (result?.archived ? 'Service archived. Historical bills were preserved.' : 'Service deleted.')); setDirty(false); navigate('/admin/billing/setup/services') } catch (err) { toast.error(err.message || 'Service could not be removed.') } finally { setDeleting(false) } }
  const leaveEditor = () => {
    if (dirty && !window.confirm('You have unsaved service changes. Leave this page and discard them?')) return
    navigate('/admin/billing/setup/services')
  }

  if (loading) return <div className="mx-auto max-w-5xl"><LoadingState label="Loading service editor..." /></div>
  if (error) return <div className="mx-auto max-w-5xl"><ErrorState message={error} onRetry={() => window.location.reload()} /></div>
  const steps = ['Details', 'Consumables', 'Pricing', 'Review']
  return <div className="mx-auto w-full max-w-5xl space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><button type="button" onClick={leaveEditor} className="inline-flex items-center gap-1 text-sm font-bold text-slate-500 hover:text-slate-800"><MdArrowBack /> Services & Pricing</button><h1 className="mt-2 flex items-center gap-2 text-2xl font-bold text-slate-900"><MdPayments className="text-amber-500" /> {editing ? 'Edit Service' : 'Add Service'}</h1><p className="mt-1 text-sm text-slate-500">Complex service setup now uses a dedicated page instead of an oversized modal.</p>{dirty && <p className="mt-1 text-xs font-black text-amber-700">● Unsaved changes</p>}</div>{editing && <button className="button-danger" onClick={() => setRemoveOpen(true)}><MdDelete /> Remove Service</button>}</div>
    <div className="grid grid-cols-4 gap-2">{steps.map((label, index) => { const n = index + 1; return <button key={label} onClick={() => n < step && setStep(n)} className={`rounded-xl border px-2 py-3 text-center text-xs font-black sm:text-sm ${step === n ? 'border-amber-400 bg-amber-50 text-amber-800' : n < step ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : 'border-slate-200 bg-white text-slate-400'}`}><span className="hidden sm:inline">{n}. </span>{label}</button> })}</div>
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
      {step === 1 && <div className="space-y-5"><div><h2 className="text-lg font-black text-slate-900">Service Details</h2><p className="mt-1 text-sm text-slate-500">Define what the service is and where it is available.</p></div><div className="grid gap-4 sm:grid-cols-2"><label><span className="form-label">Category *</span><input className="form-control mt-1.5" value={form.category} onChange={(e) => update('category', e.target.value)} />{errors.category && <p className="form-error">{errors.category}</p>}</label><label><span className="form-label">Service Name *</span><input className="form-control mt-1.5" value={form.service_name} onChange={(e) => update('service_name', e.target.value)} />{errors.service_name && <p className="form-error">{errors.service_name}</p>}</label><label><span className="form-label">Clinic</span><select className="form-control mt-1.5" value={form.clinic_type} onChange={(e) => update('clinic_type', e.target.value)}>{CLINIC_TYPES.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label><span className="form-label">Professional / Service Cost</span><input type="number" min="0" step="0.01" className="form-control mt-1.5" value={form.consultation_fee} onChange={(e) => update('consultation_fee', e.target.value)} />{errors.consultation_fee && <p className="form-error">{errors.consultation_fee}</p>}</label></div><label className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4 text-sm font-bold text-slate-700"><input type="checkbox" checked={Number(form.is_active) === 1} onChange={(e) => update('is_active', e.target.checked ? 1 : 0)} /> Active and selectable by Doctors during consultation</label></div>}
      {step === 2 && <div className="space-y-4"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-black text-slate-900">Default Consumables</h2><p className="mt-1 text-sm text-slate-500">These are starting quantities. Doctors still record actual usage during consultation.</p></div><button className="button-secondary" onClick={() => update('materials', [...form.materials, blankMaterial()])}><MdAdd /> Add Consumable</button></div>{form.materials.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center text-sm text-slate-500">No default consumables. You can continue without adding any.</div> : <div className="space-y-3">{form.materials.map((m, index) => { const item = inventoryMap.get(Number(m.inventory_id)); return <div key={index} className="rounded-2xl border border-slate-200 p-4">{m.inventory_id && !item && <div className="mb-3 rounded-xl bg-rose-50 p-3 text-sm font-bold text-rose-800">⚠ This consumable's linked Inventory item is no longer available. Replace it or remove this consumable before saving.</div>}<div className="flex justify-between"><p className="text-xs font-black uppercase tracking-wide text-slate-400">Consumable {index + 1}</p><button className="text-slate-400 hover:text-rose-600" onClick={() => update('materials', form.materials.filter((_, i) => i !== index))}><MdClose /></button></div><div className="mt-3 grid gap-3 sm:grid-cols-[1.5fr_1fr]"><label><span className="form-label">Inventory Item *</span><select className="form-control mt-1.5" value={m.inventory_id} onChange={(e) => chooseInventory(index, e.target.value)}><option value="">Select item</option>{inventory.map((inv) => <option key={inv.id} value={inv.id}>{inv.category} — {inv.name}</option>)}</select>{errors[`material_${index}`] && <p className="form-error">{errors[`material_${index}`]}</p>}</label><label><span className="form-label">Default Quantity *</span><div className="mt-1.5 flex gap-2"><input type="number" min="0.01" step="0.01" className="form-control" value={m.quantity} onChange={(e) => updateMaterial(index, 'quantity', e.target.value)} /><span className="flex min-w-20 items-center justify-center rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold text-slate-600">{m.unit_label || item?.base_unit || item?.unit || 'unit'}</span></div>{errors[`qty_${index}`] && <p className="form-error">{errors[`qty_${index}`]}</p>}</label><label className="sm:col-span-2"><span className="form-label">Notes</span><input className="form-control mt-1.5" value={m.notes} onChange={(e) => updateMaterial(index, 'notes', e.target.value)} placeholder="Optional usage note" /></label></div></div> })}</div>}</div>}
      {step === 3 && <div className="space-y-5"><div><h2 className="text-lg font-black text-slate-900">Pricing</h2><p className="mt-1 text-sm text-slate-500">Internal costing helps suggest a price; Patient Price is what Staff bills.</p></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">Consumables</p><p className="mt-2 text-xl font-black">{formatMoney(materialCost)}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">Service Cost</p><p className="mt-2 text-xl font-black">{formatMoney(serviceCost)}</p></div><div className="rounded-2xl bg-sky-50 p-4"><p className="text-xs font-bold uppercase text-sky-600">Cost Base</p><p className="mt-2 text-xl font-black text-sky-900">{formatMoney(baseCost)}</p></div></div>{Number(form.is_active) === 1 && Number(form.default_price || 0) === 0 && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">⚠ This active service currently has a ₱0 patient price and will be billed as free.</div>}{Number(form.default_price || 0) > 0 && Number(form.default_price || 0) + 0.001 < baseCost && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">⚠ Patient Price is {formatMoney(baseCost - Number(form.default_price || 0))} below the current estimated cost base.</div>}<div className="grid gap-4 sm:grid-cols-2"><label><span className="form-label">Markup %</span><input type="number" min="0" max="1000" step="0.01" className="form-control mt-1.5" value={form.profit_percentage} onChange={(e) => update('profit_percentage', e.target.value)} /><span className="form-helper">Suggested price: {formatMoney(suggested)}</span>{errors.profit_percentage && <p className="form-error">{errors.profit_percentage}</p>}</label><label className="rounded-2xl border-2 border-amber-300 bg-amber-50 p-4"><span className="text-sm font-black text-amber-900">Patient Price *</span><input type="number" min="0" step="0.01" className="form-control mt-2 bg-white text-lg font-black" value={form.default_price} onChange={(e) => update('default_price', e.target.value)} /><span className="mt-2 block text-xs text-amber-800">The standard amount Staff sees during checkout.</span>{errors.default_price && <p className="form-error">{errors.default_price}</p>}</label></div></div>}
      {step === 4 && <div className="space-y-4"><div><h2 className="text-lg font-black text-slate-900">Review Service</h2><p className="mt-1 text-sm text-slate-500">Confirm the service before saving it to Billing Setup.</p></div><div className="rounded-2xl border border-slate-200 p-5"><h3 className="text-xl font-black">{form.service_name || 'Unnamed Service'}</h3><p className="mt-1 text-sm text-slate-500">{form.category || 'No category'} · {clinicLabel(form.clinic_type)} · {Number(form.is_active) === 1 ? 'Active' : 'Inactive'}</p></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">Consumable Cost</p><p className="mt-2 font-black">{formatMoney(materialCost)}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">Suggested</p><p className="mt-2 font-black">{formatMoney(suggested)}</p></div><div className="rounded-2xl bg-amber-50 p-4"><p className="text-xs font-bold uppercase text-amber-700">Patient Price</p><p className="mt-2 text-xl font-black text-amber-900">{formatMoney(form.default_price)}</p></div></div><div className="rounded-2xl border border-slate-200 p-5"><div className="flex items-center justify-between"><strong>Default Consumables</strong><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{form.materials.length}</span></div>{form.materials.length ? <div className="mt-3 divide-y divide-slate-100">{form.materials.map((m, index) => <div key={index} className="flex justify-between gap-4 py-2 text-sm"><span>{m.material_name || inventoryMap.get(Number(m.inventory_id))?.name}</span><span className="text-slate-500">{m.quantity} {m.unit_label}</span></div>)}</div> : <p className="mt-3 text-sm text-slate-500">No default consumables.</p>}</div><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800"><MdCheck className="mr-1 inline" /> Doctors can select this service during consultation; Staff bills the saved Patient Price.</div></div>}
    </section>
    <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-between"><div>{step === 1 ? <button type="button" className="button-secondary" onClick={leaveEditor}><MdArrowBack /> Cancel</button> : <button className="button-secondary" disabled={saving} onClick={() => move(step - 1)}>Back</button>}</div><div>{step < 4 ? <button className="button-primary min-w-32" onClick={() => move(step + 1)}>Continue</button> : <button className="button-primary min-w-40" disabled={saving} onClick={save}>{saving ? 'Saving…' : editing ? 'Save Changes' : 'Add Service'}</button>}</div></div>
    <ConfirmDialog open={removeOpen} title="Remove or archive service?" message="Unused services are deleted. Services already referenced by a historical bill are archived instead so billing history remains intact." confirmLabel="Continue" loading={deleting} onCancel={() => !deleting && setRemoveOpen(false)} onConfirm={remove} />
  </div>
}
export default Admin_BillingServiceForm
