const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path')
const root=path.resolve(__dirname,'../../..');const read=(p)=>fs.readFileSync(path.join(root,p),'utf8')
const app=read('client/src/App.jsx')
const branches=read('client/src/pages/superAdminPage/redesign/Branches.jsx')
const accounts=read('client/src/pages/superAdminPage/redesign/Accounts.jsx')
const audit=read('client/src/pages/superAdminPage/redesign/Audits.jsx')
const backend=read('server/routers/branches.router.js')
const layout=read('client/src/components/layouts/BranchOperationsLayout.jsx')
test('Super Admin branch opens an independent operational portal',()=>{
 assert.match(app,/path='\/superadmin\/branches\/:branchId' element=\{<SuperAdminRoute><BranchOperationsLayout/)
 assert.match(layout,/Back to All Branches/)
 assert.match(layout,/Clinic Operations/)
 assert.match(layout,/Billing & Stock/)
})
test('Branch Admin keeps original grouped navigation design and scoped calls',()=>{
 assert.match(app,/path='\/admin' element=\{<AdminRoute><BranchOperationsLayout admin/)
 assert.match(layout,/GROUPS/)
 assert.match(layout,/fetchJson\(admin\?'\/me':'\/'\)/)
 assert.doesNotMatch(layout,/getDashboard\(/)
})
test('Branch codes are internal and generated on server',()=>{
 assert.doesNotMatch(branches,/Branch Code|b\.code/)
 assert.match(backend,/randomBytes\(8\)/)
 assert.match(branches,/role="switch"/)
 assert.match(backend,/active or upcoming appointments/)
})
test('Admin accounts include persistently stored contact number',()=>{
 assert.match(accounts,/Contact Number/)
 assert.match(accounts,/phone:a\.phone/)
 assert.match(backend,/INSERT INTO admins \(full_name,email,phone/)
 assert.match(backend,/UPDATE admins SET full_name=\?,phone=\?/) 
 assert.match(read('server/utils/schema.js'),/ensureColumn\('admins', 'phone'/)
})
test('Settings and password change normalize superadmin API role to admin',()=>{
 assert.match(read('client/src/pages/shared/SettingsPage.jsx'),/accountRole === 'superadmin' \? 'admin'/)
 assert.match(read('client/src/services/portal.service.js'),/role === 'superadmin' \? 'admin'/)
 assert.match(read('client/src/components/PasswordSecurityCard.jsx'),/role === 'superadmin'/)
})
test('Audit UI displays readable names and only changed, non-sensitive fields',()=>{
 assert.match(backend,/actor_name/)
 assert.match(audit,/changesFor\(detail\)/)
 assert.match(audit,/const redact=/)
 assert.doesNotMatch(audit,/Account #/)
 assert.doesNotMatch(audit,/\[REDACTED\]/)
})
