const escapeHtml = (value) => String(value ?? '')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;').replace(/'/g, '&#039;')

const line = (label, value) => value ? `<div class="line"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong></div>` : ''

export const printConsultationRecord = ({ patient, diagnosis, notes, prescriptions = [], doctorName, specialty, prcLicense, date, clinic, services = [] }) => {
  const popup = window.open('', '_blank', 'width=900,height=1100')
  if (!popup) throw new Error('Pop-up printing is blocked by the browser. Allow pop-ups and try again.')
  const rx = prescriptions.filter((item) => String(item?.medicine || '').trim())
  const performed = services.filter((item) => item?.service_name)
  const logo = `${window.location.origin}/logo.png`
  popup.document.open()
  popup.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Carait Consultation Record</title><style>
    @page{size:A4;margin:14mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#172033;margin:0;font-size:11px;line-height:1.45}header{display:flex;align-items:center;gap:14px;border-bottom:2px solid #223b5a;padding-bottom:10px;margin-bottom:14px}header img{width:64px;height:64px;object-fit:contain}.brand h1{font-size:17px;margin:0;color:#17324f}.brand p{margin:2px 0;color:#607086}.title{text-align:center;font-size:15px;font-weight:800;letter-spacing:.08em;margin:12px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:7px 18px}.line{display:flex;gap:8px;border-bottom:1px solid #e5e9ef;padding:4px 0}.line span{color:#718096;min-width:90px}.box{border:1px solid #d9e1ea;border-radius:8px;padding:10px;margin-top:10px}.box h2{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#66758a;margin:0 0 6px}.rx{padding:7px 0;border-bottom:1px solid #edf0f4}.rx:last-child{border-bottom:0}.rx strong{font-size:12px}.muted{color:#64748b}.signature{margin-top:36px;width:220px;border-top:1px solid #172033;padding-top:4px}.footer{margin-top:18px;color:#8a98a9;font-size:9px;text-align:center}@media print{button{display:none}}
  </style></head><body><header><img src="${logo}" alt="Carait logo"><div class="brand"><h1>${escapeHtml(clinic?.clinic_name || 'CARAIT MEDICAL AND DERMATOLOGY CLINIC')}</h1><p>${escapeHtml(clinic?.address || '')}</p><p>${escapeHtml([clinic?.phone, clinic?.email].filter(Boolean).join(' • '))}</p></div></header><div class="title">CONSULTATION RECORD</div><div class="grid">${line('Patient', patient?.name)}${line('Age / Sex', [patient?.age,patient?.sex].filter(Boolean).join(' / '))}${line('Visit Date', date)}${line('Doctor', doctorName)}${line('Specialty', specialty)}${line('PRC License', prcLicense)}${line('Reason', patient?.reason)}</div>${diagnosis?`<section class="box"><h2>Diagnosis</h2><div>${escapeHtml(diagnosis)}</div></section>`:''}${notes?`<section class="box"><h2>Clinical Notes</h2><div>${escapeHtml(notes).replace(/\n/g,'<br>')}</div></section>`:''}${performed.length?`<section class="box"><h2>Services Performed</h2>${performed.map(s=>`<div class="rx"><strong>${escapeHtml(s.service_name)}</strong>${s.quantity?` <span class="muted">× ${escapeHtml(s.quantity)}</span>`:''}</div>`).join('')}</section>`:''}<section class="box"><h2>Prescription</h2>${rx.length?rx.map((r,i)=>`<div class="rx"><strong>${i+1}. ${escapeHtml(r.medicine)}</strong><div class="muted">${[r.dosage&&`Dosage: ${r.dosage}`,r.frequency&&`Frequency: ${r.frequency}`,r.duration&&`Duration: ${r.duration}`].filter(Boolean).map(escapeHtml).join(' • ')}</div>${r.notes?`<div>${escapeHtml(r.notes)}</div>`:''}</div>`).join(''):'<div class="muted">No prescription recorded.</div>'}</section><div class="signature">Doctor's Signature</div><div class="footer">Generated by Carait Clinic Management System</div></body></html>`)
  popup.document.close()
  popup.focus()
  popup.onload = () => { popup.print() }
}
