import { useState } from 'react'
import { MdLock, MdMail, MdSms } from 'react-icons/md'
import { useAuth } from '../context/AuthContext'
const PasswordSecurityCard = () => {
  const { role } = useAuth(); const [step,setStep]=useState(0); const [code,setCode]=useState(''); const [pw,setPw]=useState(''); const [confirm,setConfirm]=useState(''); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false)
  const request = async()=>{setBusy(true);setMsg('');try{const r=await fetch(`/api/${role}/security/password/request-code`,{method:'POST',credentials:'include'});const d=await r.json();if(!r.ok)throw new Error(d.message);setMsg(d.message);setStep(1)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
  const change=async()=>{if(pw!==confirm)return setMsg('Passwords do not match.');setBusy(true);setMsg('');try{const r=await fetch(`/api/${role}/security/password/change`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,new_password:pw})});const d=await r.json();if(!r.ok)throw new Error(d.message);setMsg('Password changed successfully.');setStep(0);setCode('');setPw('');setConfirm('')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
  return <div className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="flex items-center gap-2 font-bold text-slate-900"><MdLock/> Account Security</h2><p className="mt-1 text-sm text-slate-500">Change your password using a one-time verification code.</p></div>{role==='patient'?<MdSms className="text-xl text-slate-400"/>:<MdMail className="text-xl text-slate-400"/>}</div>{msg&&<p className="mt-4 rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-600">{msg}</p>}{step===0?<button onClick={request} disabled={busy} className="mt-5 rounded-2xl border border-slate-200 px-5 py-3 text-sm font-bold text-slate-700 hover:bg-slate-50">{busy?'Sending...':'Change Password'}</button>:<div className="mt-5 grid gap-3"><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="6-digit verification code" className="rounded-2xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-sky-400"/><input type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder="New password" className="rounded-2xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-sky-400"/><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Confirm new password" className="rounded-2xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-sky-400"/><div className="flex gap-2"><button onClick={()=>setStep(0)} className="rounded-xl border border-slate-200 px-4 py-2 text-sm">Cancel</button><button onClick={change} disabled={busy||code.length!==6||!pw} className="rounded-xl bg-[#0b1a2c] px-4 py-2 text-sm font-bold text-white disabled:opacity-40">{busy?'Saving...':'Verify & Change'}</button></div></div>}</div>
}
export default PasswordSecurityCard
